### ISSUE TITLE
"Could not find a good path to install to"

### ISSUE THREAD

**Issue by gCurtisCT** [Benvie/node-Windows#12]
When I try to run an app that's just

    var windows = require('windows')

I get this error:

    path\to\app\node_modules\windows\lib\runnable.js:27
    throw new Error('Could not find a good path to install to');
        ^
    Error: Could not find a good path to install to
      at Object.<anonymous>
    (path\to\app\node_modules\windows\lib\runnable.js:27:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> path\to\app\node_modules\windows\index.js:4:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by justinmchase** [comment]
:+1: Why is it trying to install things?

**Comment by spiffytech** [comment]
:+1:

**Comment by roman-yerin** [comment]
:+1:
